const products = {
  data: [
    {
      Rank: 1,
      Calmar: 3.96,
      name: "Selling with re enter",
      AvgProfit: 319.54,
      Overall: 381845,
      price: "-",
      Win: 0.65,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 2,
      Calmar: 3.62,
      name: "	strategy_name",
      AvgProfit: 216.31,
      Overall: 268872.5,
      price: 500,
      Win: 0.64,
      Action: "Buy",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 3,
      Calmar: 3.42,
      name: "	Based on premium and",
      AvgProfit: 208.51,
      Overall: 255425,
      price: "-",
      Win: 0.64,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 4,
      Calmar: 3.42,
      name: "strategy_name",
      AvgProfit: 208.51,
      Overall: 159425,
      price: "-",
      Win: 0.67,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 5,
      Calmar: 3.42,
      name: "strategy_name",
      AvgProfit: 208.51,
      Overall: 359125,
      price: "-",
      Win: 0.47,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 6,
      Calmar: 3.01,
      name: "Based on premium wit",
      AvgProfit: 185.77,
      Overall: 135980,
      price: "-",
      Win: 0.49,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 7,
      Calmar: 2.79,
      name: "strategy_name",
      AvgProfit: 218.49,
      Overall: 267867.5,
      price: "-",
      Win: 0.6,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 8,
      Calmar: 2.62,
      name: "Wait and trade_Save",
      AvgProfit: 161.9,
      Overall: 178252.5,
      price: "-",
      Win: 0.63,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 9,
      Calmar: 2.44,
      name: "iron condor",
      AvgProfit: 137.51,
      Overall: 176420,
      price: "-",
      Win: 0.65,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      Rank: 110,
      Calmar: 2.04,
      name: "strategy_name",
      AvgProfit: 198.66,
      Overall: 244555,
      price: "-",
      Win: 0.62,
      Action: "View",

      id: "1000",
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
  ],
};

export default products;
